name: uncertainty_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - pyod
  - requests
  - scikit-learn
  - scipy
  - pytorch
  - ipykernel #required for notebooks
  - openpyxl
  - properscoring
  - ucimlrepo
  - seaborn
  - uncertainty-toolbox
  - cpuonly
  - pip
  - tensorboard
  - pyro-ppl
  - gpytorch